# 산포통계

In [1]:
import numpy as np
from scipy import stats
import pandas as pd

### 분산 계산

In [4]:
x = [1,2,3,4,5]
print(np.var(x,ddof = 0)) #해석 : 분산을 계산(var) 그냥하거나 ddof를 0으로 주면 모집단 계산
print(np.var(x,ddof = 1))  #표본 데이터의 분산을 계산할 때 분모(n-1) / 모집단이 아닌 표본
print(np.array(x).var())
print(pd.Series(x).var(ddof = 0)) #numpy가 아닌 pandas series에도 있다

2.0
2.5
2.0
2.0

#### 분산 계산식

* sum(x_i - 평균)**2 / n < 모집단 데이터의 분산 계산식
* sum(x_1 - 평균)**2 / (n-1) < 표본 데이터의 분산 계산식
* ddof : 자유도 : 데이터의 산포도를 나타내는 지표
  * ddof=1(기본값) = 자유도 n-1 : 표본 평균을 사용한 분산이 모분산을 편향 없이 추정하도록 보정함.
  * ddof=0 = 자유도 n : 표본 전체를 모집단처럼 취급하여 표준편차를 계산, 모평균을 아는 경우에 사용하며 편향이 발생할 수 있음.
  * 편향이 발생할 수 있다/없다 = 결과값이 실제 표준편차보다 작게(과소평가) 나오는 경향이 있다
     1. 표본 분산 공식은, 표본의 각 데이터(x_i)와 표본 평균의 차이를 사용
     2. 데이터와 데이터 자체의 평균 간의 거리는 데이터와 '다른' 평균(모집단 평균) 간의 거리보다 항상 작거나 같습니다.
     3. 결과적으로 계산된 표준 분산은 실제 모집단 분산보다 항상 작게 나오려는 경향이 있음. **통계는 일반적으로 표본을 통해 모집단의 특성을 추론하는 방법론이기 때문**

### 표준편차 계산

In [6]:
x = [1, 2, 3, 4, 5]
print(np.std(x, ddof = 1))
print(np.array(x).std(ddof = 0))
print(pd.Series(x).std(ddof = 1))

1.5811388300841898
1.4142135623730951
1.5811388300841898

### 변동계수의 필요성
* 분산과 표준편차 모두 값의 스케일에 크게 영향을 받아 상대적인 산포를 보여주는데 부작합함.
* 변동 계수 = 표준편차 / 평균

In [7]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

print(np.std(x1, ddof = 1))
print(np.std(x2, ddof = 1))

1.5811388300841898
15.811388300841896

In [8]:
print(stats.variation(x1)) # 변동 계수
print(stats.variation(x2))

0.47140452079103173
0.4714045207910317

In [9]:
print(np.std(x1, ddof = 1) / np.mean(x1))
print(np.std(x2, ddof = 1) / np.mean(x2))

0.5270462766947299
0.5270462766947299

### 스케일링
* 둘 이상의 변수의 값을 상대적으로 비교할 때 사용

In [10]:
import numpy as np
import pandas as pd

In [11]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

In [12]:
x1

array([1, 2, 3, 4, 5])

In [13]:
x2

array([10, 20, 30, 40, 50])

In [17]:
# Standard Scaling
z1 = (x1 - x1.mean()) / x1.std()
z2 = (x2 - x2.mean()) / x2.std()

print(z1)
print(z2)

#결과 해석 : 가운데 0을 기준으로 좌우로 얼마나 떨어져있는지를 보여주는 것.
#결과는 각자 1, 2, 3, 4, 5가 스케일링 된 값이다.

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

In [15]:
# Min-max Scaling
z1 = (x1 - x1.min()) / (x1.max() - x1.min())
z2 = (x2 - x2.min()) / (x2.max() - x2.min())

#결과 해석 : 0과 1사이 값으로 수준이 맞춰진다.

print(z1)
print(z2)

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]

In [16]:
# sklearn을 이용한 스케일링을 위한 데이터 준비
X = pd.DataFrame({"X1":[1, 2, 3, 4, 5],
    "X2": [10, 20, 30, 40, 50]})

X

   X1  X2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

아래 열을 수행하기 전에, 미리 anaconda prompt로 아래 사항을 install해주어야 한다.
* pip install scikit-learn

In [19]:
# scikit learn 의 MinMaxScaler 적용
# 0 ~ 1 데이터 스크케일링함
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() # 인스턴스화
Z = scaler.fit_transform(X) # fit_transform => ndarray
pd.DataFrame(Z, columns=['X1', 'X2'])

     X1    X2
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00

In [20]:
# 표준 정규분포에 따라서 데이터의 수준을 맞춤
# 표준 정규분포 : 
from sklearn.preprocessing import StandardScaler

In [21]:
ss_scaler = StandardScaler() # 인스턴스화
Z = ss_scaler.fit_transform(X) # fit_transform => ndarray
pd.DataFrame(Z, columns=['X1', 'X2'])

         X1        X2
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

# 데이터 표준화 하기

데이터 프레임 만들기

In [18]:
import pandas as pd #왜 오류 나는 지 모르겠음

In [ ]:
pd.DataFrame(
    {
        "X1" : {1,2,3,4,5},
         "X2" : {10,20,30,40,50}
    }
            )  ##해당 셀 실행 안함

In [19]:
# 표준 정규분포에 따라서 데이터의 수준을 맞춤
# 표준 정규분포 : 
from sklearn.preprocessing import StandardScaler

In [20]:
# Standard scaling
from sklearn.preprocessing import StandardScaler

ss_scaler = StandardScaler() # 인스턴스화
S = ss_scaler.fit_transform(X) # fit_transform => ndarray
pd.DataFrame(S, columns=['X1', 'X2'])

NameError: name 'X' is not defined

# 범위와 사분위 범위 계산

In [22]:
# np.random.normal(평균, 편차, size = 갯수)
x = np.random.normal(100, 20, size = 1000)
x

array([109.77467369,  75.19552425,  99.47557443,  96.89736055,
        73.56259603,  62.60203093, 109.04785886, 107.47356557,
        88.30756552,  94.11403563, 116.35085577, 110.84755522,
       117.87041515, 130.08363606, 103.44050336, 127.31475261,
        98.86259292,  96.70007545, 114.12604639,  60.28922533,
        68.66616337, 118.93378838, 104.47393358,  81.2026178 ,
       112.92773634,  91.84805985, 104.35936714, 148.28886207,
        67.98598142, 107.28351364,  84.78196359,  68.61236124,
        84.40824284, 110.95823694,  60.36584613, 158.65180132,
        73.39001935,  79.05928426, 110.49369409,  94.58489428,
       111.80064648,  89.83156743,  85.120574  , 115.42111878,
       121.12638383,  95.21801224, 117.6511501 ,  75.51301242,
       100.65254135,  78.00435059,  89.79773208,  57.67880386,
       104.90894139,  87.91649303, 106.71830301, 123.67755103,
        95.6785693 ,  96.50848696, 108.45488917,  86.7529379 ,
        92.80210704,  81.55187533, 105.55058684, 117.57354862,
        86.12591068,  96.11235814, 102.79516225, 125.42744839,
       124.68302288,  98.03197641,  88.21184547, 122.11531267,
        91.18020581,  94.2917021 ,  87.47837916, 123.5921462 ,
        84.44457862,  83.21401435,  98.28583174, 122.51905397,
        93.84009338, 112.4872697 , 116.87648393,  82.74520456,
        90.77986686, 131.84908768, 133.20677513, 114.8219959 ,
       109.5536818 ,  78.59897362, 105.64868519,  86.6405738 ,
       113.81720935,  87.83435868, 100.37844221,  75.36876698,
        80.7441395 ,  99.96277871,  95.06114222,  71.33451942,
        87.63570327, 114.48618235,  77.45388088,  90.28464488,
       140.63309183,  77.25130786, 106.11874096, 104.92003616,
       116.40662847,  92.36203227,  91.52279237,  87.03313847,
        95.12509152, 107.9062607 , 128.06462449,  99.14847532,
        79.33599403,  74.83238547,  95.93077086,  82.29197856,
       100.05554553,  74.63710107, 111.64693694,  85.25604798,
       105.04481507,  84.86703852,  76.96858272, 107.70653763,
        78.91571005, 109.51144722,  88.94434782,  83.39903363,
       121.8902997 ,  86.62715163, 118.17835739,  96.88858726,
        89.55302518, 137.23070844, 124.39695043, 145.4629945 ,
       118.8265713 ,  69.93729411,  99.7371571 , 122.12007325,
       110.88872333, 101.10258319, 120.34106353, 113.3107063 ,
        96.89394712, 119.7576277 ,  80.7697607 ,  97.13961511,
       104.67238631,  72.54212938, 127.04075426, 123.59930875,
        85.47278283,  95.17187178, 128.10426882,  88.53300127,
       122.24177709,  90.5464428 ,  89.71606111,  99.42546697,
       100.1934959 , 117.82484391,  83.22651396,  64.89888683,
       120.17918823, 115.20269513, 107.1940223 ,  87.14445302,
        65.32373446, 108.55738846,  76.72838762, 118.44571047,
        91.2414377 ,  92.94716484,  88.72351279, 126.5610638 ,
       144.4310221 ,  99.862976  , 137.26670746, 100.32507973,
       103.91929758, 112.89609225,  85.07400786,  99.29975978,
       102.01594596,  73.92704739,  86.90556958, 117.40587131,
       106.38435808,  71.74251548,  87.97502155, 122.86810436,
       118.08653786,  95.7131464 ,  89.06806884,  94.4802465 ,
       100.08976708, 116.16043279,  90.85603146,  84.85387234,
        75.63361799,  85.84158672, 105.57723713,  98.81516825,
       106.58548042, 105.55565154,  89.4857723 ,  62.42243944,
       108.22506779,  57.30637628,  99.96665643, 112.98241689,
        80.67134986, 109.25597655,  61.89158768, 102.88109182,
       120.12669035,  74.33192844,  79.85930156,  65.73137656,
       115.15683871, 109.70672119,  85.90251853, 125.79368489,
        91.54867825, 113.44204611, 119.84618836,  74.10195028,
       130.6925012 ,  77.91352886,  75.16875073,  78.2292316 ,
       114.46590262, 126.71501116, 104.47427022,  68.51011526,
       110.37587457,  96.88220106,  78.14115243, 117.98510665,
        85.40019522, 132.63674835, 120.56277038, 113.81732956,
        84.81155535,  77.16523747,  74.58906142,  70.83672574,
       101.64483889, 103.08976226,  85.61068014, 108.93335946,
       110.10930298,  86.4851374 , 104.80186677, 111.84906311,
       106.83860594,  87.69145778, 111.03251787,  54.01850815,
       115.5579256 ,  83.70703218,  75.88743715, 112.52135969,
        87.979047  ,  97.14916893, 110.9090681 ,  94.42946165,
        95.62896352, 111.04558809, 120.11066449, 103.61425404,
        78.93898291,  89.80003129,  91.92089529, 103.61181722,
        74.49564608, 109.74159387, 114.11929567, 119.25294582,
       126.72193253, 109.89784682,  84.44197202, 101.29524207,
        88.56981537, 106.92438708, 107.19178194, 118.67085576,
       107.86971266,  90.27549025, 103.04544294,  97.56634739,
       133.53745664, 124.34894539,  89.12129925, 125.71290521,
        66.24411979,  73.84285631, 132.16923436,  48.09408459,
        86.01217439, 132.22563057,  96.40341718,  88.25093884,
        85.57769619, 119.88263447,  94.42126638,  78.52132173,
       100.1293789 , 105.18411861,  64.63087578,  64.77167653,
        85.54671749,  95.72289045, 116.66628816,  97.81149749,
       123.47557943,  78.02063293, 131.16413775, 131.6191656 ,
       103.09967346, 111.05011354,  84.5605641 , 112.72056204,
       112.29605705, 114.26567927,  97.23802847, 100.18537224,
        71.59009974, 103.28039244, 168.42894326,  50.99969577,
        82.45032241,  68.72619931, 119.31612451,  99.0724478 ,
        43.54879582,  87.55202867,  54.4109282 ,  88.31781286,
       111.43914767, 108.92935498,  84.18811133, 105.93920841,
        97.21665665,  99.56346604, 119.74142724,  86.74646852,
       106.08446052, 104.30295408,  53.6813174 ,  95.12131276,
        93.99047997,  91.67785286,  84.2831657 , 145.11128194,
       110.24725234, 110.67836702, 116.03732456,  88.07296696,
       109.45398762,  96.04469023,  87.90356641, 104.93205806,
        88.51093169,  76.16018703,  70.46948183,  95.13483573,
       115.55796295,  75.03263326,  93.01073649, 118.23746862,
        97.34535866, 136.17009804,  87.8228051 ,  92.5394662 ,
        85.76974802, 136.98144749, 121.73722983,  81.01525848,
       100.5629259 ,  97.80212222, 114.76799875, 102.73020308,
       123.43436302, 111.50187926, 104.88985209,  90.5825519 ,
        97.68730109, 113.25187093, 100.95803309, 108.30427698,
        86.61869193,  97.13313069,  90.39175246,  88.07731961,
        89.09219091, 100.91503499,  86.71692696,  86.69111012,
        90.0071748 ,  98.62532267,  95.26489045, 104.58627564,
       130.46787239, 102.06198909, 102.68989141, 107.7369451 ,
        99.65121909,  75.22267973, 117.93339788,  85.69440765,
       122.32152053, 105.36531251,  99.46531935, 131.00967181,
        69.25257871,  65.42079348,  98.11533802, 119.75089755,
       119.88919302, 114.6780006 ,  98.58206131, 124.03942061,
       121.05145933,  96.45030228,  95.13997685,  53.98838097,
        76.83760179, 103.56579246, 108.74404411,  86.31668485,
       130.34835963,  57.73527502, 136.15654025, 102.44073285,
        72.6811215 ,  86.38274916, 122.02487211,  75.2321437 ,
       119.55372613, 107.39673894, 132.21632463,  91.16715134,
        93.38946196, 103.92939017,  86.32373941,  95.03466623,
        92.5171247 , 100.21090412,  66.42374629,  80.61027672,
       128.00831733,  54.01416848,  92.94354112,  86.32362737,
        94.40422849,  48.893048  , 116.96888967,  71.463808  ,
        86.06100708, 104.14826401, 102.03853794, 102.24695117,
        99.42703117,  97.13930861,  92.59638836, 122.12880511,
        93.26345015, 138.15990636,  87.62366614, 113.68502046,
        90.66840056,  63.02210699, 104.81128865,  99.89134765,
        73.21402275, 125.05995276, 111.57144301,  85.35690945,
        90.60497007, 106.41419975, 102.1046585 , 107.06496554,
       131.9643657 ,  93.13426696, 103.81368171,  89.53052089,
        78.32746157, 114.75783544,  84.04527379,  78.19823452,
       109.31881663, 111.4695718 , 115.63484253,  81.35963592,
       134.0859584 ,  87.48941577, 121.81530632,  81.79503719,
        84.14927086,  93.46829541, 121.9560132 , 120.01323482,
        80.18810241,  93.87454453,  62.50224783, 117.1908634 ,
       114.24717287, 107.90189079,  86.00852482, 142.31758722,
        93.21859116, 135.89555462,  71.20203918,  98.53812583,
        92.45286797, 116.9137731 ,  71.00995631,  76.5192696 ,
       111.55349406, 110.96541313,  68.67276132, 111.70911141,
       104.47439761, 118.07312664,  87.42489834, 104.43000918,
        92.39574479, 126.21971038, 116.33914083, 122.23756228,
        66.61813105, 101.08573826,  63.41453609,  98.69565386,
       105.64350028,  89.09427024,  91.95402194,  93.30002227,
        95.20581598, 113.75821297, 111.28439852,  96.12609813,
        77.76059758, 121.74189323,  72.10934725, 110.10650741,
        97.16118291,  93.129015  , 106.28828357,  99.70060353,
       101.54332325, 113.55106086,  81.70632273,  67.81797046,
        99.99499501,  70.57924074,  65.94240161,  74.00193876,
        73.49232979, 114.82648163,  45.39636827, 105.67435676,
       105.05449217, 127.14529306,  84.02618524,  84.29399809,
       102.99995284,  78.68988462, 106.94955193,  65.46575679,
        81.57811342,  95.38134239,  74.05005942,  88.63135744,
        80.82762759, 100.3441929 ,  76.60971339,  84.27863796,
       128.70753061, 100.60663891,  84.13608456,  98.00880359,
        95.36961526, 106.15452335,  97.44480561,  90.48181274,
        63.63668129, 117.98822653, 166.96857923, 107.93745132,
       129.28065858, 126.28223187, 132.45677508,  85.30248142,
        73.85518523, 113.3421833 ,  99.33837821, 122.47619896,
       112.47246109, 107.59543902,  73.76490406, 102.04134225,
        95.29047393,  57.06999566, 117.59819554,  98.3923374 ,
       122.34378511,  93.51685341, 117.43148193,  97.78852666,
        92.57904262,  88.16660011, 106.60831215,  96.67115808,
        97.41926793, 113.56038245, 110.30670883, 102.94964966,
       111.08938646, 105.59789396,  83.47707934, 111.04043552,
       125.39044909,  91.64775934,  81.63510827,  90.37276669,
        98.84592281,  92.23716267,  68.07090656,  94.73072665,
        96.50670719,  87.30875508,  98.74129325, 125.69063472,
        98.90955036,  79.74992617,  89.34118689, 111.4910783 ,
        88.78003627, 109.43808962, 102.56115081, 118.22041911,
        88.78537011,  74.87701672, 102.93270276, 105.0529511 ,
       115.16514254, 105.46975358,  90.64112464,  57.74156208,
       106.31425564, 103.76914716, 104.964971  ,  68.90116618,
       112.57796735,  91.40146871,  97.31268184, 103.62413464,
        80.23597295, 137.03696124, 107.02977287, 103.12427634,
        91.18801618,  81.62818805, 152.13528183,  95.49889717,
        97.68571009,  82.65649022, 117.66732366,  96.99692229,
       100.9671936 , 112.03895788,  92.8190866 ,  90.51937344,
       104.45910664, 113.46609445, 114.62837516,  91.87724917,
        93.49608641,  81.94905219, 109.39864319, 102.56065595,
       108.30056048, 115.60517435, 110.45887846, 123.06994871,
        94.08115205,  80.17885224,  91.18916301,  96.63579588,
       135.27483359, 102.21277001, 111.11594435, 101.7004677 ,
       121.99950522,  83.15538469,  98.08873141,  55.12425975,
        46.24613512, 118.90774557,  84.69232946,  80.28164446,
        94.15546403, 108.70656479,  75.07976541,  82.6808793 ,
        64.87772796, 101.05164716, 104.13355318, 112.76918683,
       101.80119129, 111.74521546,  88.07988287,  92.35477603,
       110.04270238,  75.45383817, 135.46127884, 107.24293098,
        79.31181548, 109.66241497,  75.09746267,  65.1275228 ,
        88.45909609, 104.21160828,  84.65615098, 125.83251639,
       131.11925357,  81.9942164 , 111.33619061,  90.26537257,
       109.77924085, 112.74057227, 111.04426086,  86.03958076,
        88.86944704,  87.93269951,  78.82243837, 105.36662117,
        91.1131286 ,  99.25134202, 109.95498624, 101.6960973 ,
       100.49897708, 105.2852986 ,  99.27925864,  89.92216548,
       127.29821084, 126.54498906,  99.29888281, 103.29348807,
       121.48414561, 118.60852664,  74.2083262 , 102.95418333,
       112.30731199, 106.06085089,  92.39838066, 116.57529329,
       125.08528211, 112.24663263, 127.60791438,  83.34588418,
        76.10548663,  92.38089344, 102.12979445,  97.34401611,
       118.61787985,  96.52794681,  67.27767212,  90.38448578,
        63.73558203, 107.6559539 , 133.8422256 , 107.51552432,
        96.62157696,  83.27814123, 108.43753353,  87.20919957,
       144.94351598,  88.09915029,  95.2892792 ,  86.40935139,
       110.41806801, 114.53224296,  73.217955  ,  82.15637151,
       139.64771883, 115.73556216, 103.73881664, 120.48470559,
       100.39630634, 100.09905676,  71.4549841 , 115.69506837,
       123.60698474,  79.87930561, 115.01801348,  99.35023076,
        92.90144987, 111.98629009, 168.69423619, 135.53179593,
       115.94987823,  76.07929239,  85.52972345, 110.38208305,
        84.8092585 , 109.64031343,  82.60910042, 106.45927071,
       147.89311729,  76.81531005,  96.1412889 , 141.96467419,
        72.73667137,  89.14175439,  99.28635106,  80.99689581,
        63.06369015, 111.65637488,  91.85925403, 106.5541244 ,
        94.81727019, 114.22729171, 114.17810845,  85.40060992,
        87.98603029,  93.99949928,  97.55553673, 126.47931576,
        98.49691823,  84.48311138, 114.66865742,  86.9502286 ,
        73.19935426, 114.7257299 ,  95.82318086, 104.11056701,
        93.5376405 , 119.11947481,  89.71887131, 111.60927677,
       123.3743725 ,  58.72003338,  86.46329703,  73.37302214,
        69.56474646,  67.11176142,  71.82394769, 104.70182438,
        83.04811421, 102.12218865,  96.53786165, 122.80081216,
        67.51778248, 110.33628232,  81.05444689,  59.85187449,
        98.98892526,  94.2554093 ,  71.61753332,  85.68102373,
        90.6175203 ,  91.88808204,  73.70507388, 112.85072773,
        96.64357019,  92.03904427,  95.26093225,  88.57439683,
       115.70894266,  85.67326644, 115.46549356, 116.396186  ,
        66.01097318, 131.67043756, 125.67470576, 108.48101363,
       102.46562939,  74.17590073,  73.85671923,  78.77111636,
       104.38209773, 109.92630814, 106.46140117, 107.72781077,
       126.11624149, 129.77956702,  98.57500075, 105.22479265,
        73.25708552, 103.83475981,  74.46576894,  76.67260909,
       124.73357347, 102.23042916, 108.71263519,  99.99964874,
        93.88573   , 130.70422841, 111.79568691,  96.37609089,
        93.61816774, 114.57911955,  73.82328974, 128.43100205,
        95.84568942, 105.61961205,  71.78413907, 109.55670218,
        98.61428188, 109.92645777,  88.57954282, 103.23802616,
       120.31893935,  91.72791701,  80.67303947, 102.81473758,
        64.90161025,  89.26329656, 109.88163606, 101.74009915,
        74.97459422, 115.44397157, 111.16460172, 123.19210097,
       100.25251026, 107.66233486, 108.36757036, 120.58359614,
        91.69431852,  62.11275439,  81.95785272, 136.08166676,
        92.98933235, 114.82471525,  96.77527371, 110.60886879,
        96.89764309, 112.32005318,  91.21638113,  80.43987931,
       100.4822006 , 111.88383051,  77.2259792 ,  77.37761398,
        91.18866392, 103.42401613, 104.77586365, 112.61896365,
        99.88918873, 107.07944356,  93.85683242, 119.06298002,
        92.97047238, 102.63413092, 115.4479001 , 123.24741887,
       116.31947874,  90.40591234, 104.17024358, 115.50626204,
       100.73783457, 114.00870481, 108.04626284,  93.37462009,
       149.75422688, 107.28845006,  78.94544842, 121.52612277,
       110.79413155, 108.86960976,  75.66303463,  82.5749933 ,
       102.27767628, 116.60770805,  61.71073052, 104.37161658,
        65.81789334, 108.17608881, 104.95936423,  96.27085987,
       115.83423842,  83.66899542,  90.80806074,  89.44379133,
        90.22883679,  99.05869286, 114.09304529, 110.78915904,
       123.94518551, 130.42259456,  89.60523975,  85.93258571])

In [23]:
print(np.ptp(x))
print(np.max(x) - np.min(x))

125.14544037680966
125.14544037680966

In [24]:
print(np.quantile(x, 0.75) - np.quantile(x, 0.25))
print(stats.iqr(x))

25.1688811884585
25.1688811884585